server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true
    username: root
    password: '0123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        highlight_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret-key: eriojjgrieojq8386**pwdelow0-jtri9jebt8-blyk9ewrh887ghtrteythrt
  expiration-time-minutes: 1000

user:
  session:
    expiration:
      time:
        days: 7
  password-reset-token-expiration-minutes: 60

report:
  escalation-period-hours: 1
  locking-period-minutes: 30